POSTS_DIR = "_posts"
MEMBERS_DIR = "_profiles"
DATA_DIR = "_data"
GALLERY_DIR = "gallery"
FILE_ALL_PUBLICATIONS = "publications_all.yml"

ARG_SITE_DIR = "site_dir"
ARG_CUSTOM_NEWS_ARTICLES_ID = "custom_news_articles_doc_id"
ARG_MEMBERS_SHEET_ID = "members_sheet_id"
ARG_PHOTOS_SHEET_ID = "photos_sheet_id"
ARG_SELECTED_PUBLICATIONS_SHEET_ID = "selected_publications_sheet_id"
ARG_RESEARCH_DOC_ID = "research_doc_id"
ARG_GRANTS_SHEET_ID = "grants_sheet_id"
