name: build-website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
permissions:
      contents: write
      pages: write
      
jobs:
  run-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r python_generator/requirements.txt

      - name: Install Firefox
        run: |
          sudo snap remove firefox
          sudo install -d -m 0755 /etc/apt/keyrings
          wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
          echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
          echo '
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
          ' | sudo tee /etc/apt/preferences.d/mozilla
          sudo apt update && sudo apt install -y firefox

      - name: Install Ruby and Jekyll
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          gem install jekyll bundler --user-install

      - name: Run Python generator
        env:
          CUSTOM_NEWS_ARTICLES_DOC_ID: ${{ secrets.CUSTOM_NEWS_ARTICLES_DOC_ID }}
          MEMBERS_SHEET_ID: ${{ secrets.MEMBERS_SHEET_ID }}
          PHOTOS_SHEET_ID: ${{ secrets.PHOTOS_SHEET_ID }}
          SELECTED_PUBLICATIONS_SHEET_ID: ${{ secrets.SELECTED_PUBLICATIONS_SHEET_ID }}
          RESEARCH_DOC_ID: ${{ secrets.RESEARCH_DOC_ID }}
        run: |
          python -m python_generator --site_dir ./ --custom_news_articles_doc_id $CUSTOM_NEWS_ARTICLES_DOC_ID --members_sheet_id $MEMBERS_SHEET_ID --photos_sheet_id $PHOTOS_SHEET_ID --selected_publications_sheet_id $SELECTED_PUBLICATIONS_SHEET_ID --research_doc_id $RESEARCH_DOC_ID

      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build -s ./ -d ./_site
          

      - name: Upload generated files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add .
          git commit -m 'Add generated files'
          git push origin main
